### ISSUE TITLE
plugin confusion [SOLVED]

### ISSUE THREAD

**Issue by LeoBdt** [HighLev-PM/ChestFinder#1]
c'est pas le plugin d'ayzrix par hasard xD

**Comment by Palente** [comment]
Vous avez du mal lire l'auteur c'est Virvolta

**Comment by LeoBdt** [comment]
@Palente je pose ça là. 
[UnclaimFinder.zip](https://github.com/HighLev-PM/ChestFinder/files/2893913/UnclaimFinder.zip)

**Comment by LeoBdt** [comment]
Alors monsieur @Palente avant de critiquer ma lecture, apprends à formuler correctement des mots en anglais et français, ta bio ainsi que tout tes répertoires sont des vrais calvaire.

**Comment by Virvolta** [comment]
si tu regarde bien chaque developpeur on une (ecriture) c'est la form dont t'il mais leurs function si tu compare ce plugins au autre tu vois bien que la forms est la meme de plus moi j'ai une particularité je fait beaucoup d'espace et de saut de ligne donc oui je te confirme ayzrix a volé mon plugin.

**Comment by LeoBdt** [comment]
Donc j'ai payé un plugin volé ? @Virvolta :issou:

**Comment by Virvolta** [comment]
oui car tu peux voir que le plugins de ayzrix a exactement la meme ecriture que mon itemeffect ou itemarmor .....

**Comment by LeoBdt** [comment]
Chelou, de plus dans sa vidéo il dit que les dev sont Bluzzi et lui. Bluzzi m'a dit qu'il l'a juste aidé. Ce plugin est réellement à qui 😢

**Comment by Virvolta** [comment]
j'etais sur le discord de bluzzi est je confirme que bluzzi avais donné un code a ayzrix mais c'est moi qui est donné l'idée de crée un task dans le onheld et ayzrix a fait a sa sauce moi j'ai fait a ma sauce et a vraie dire ayzrix a preferé ma sauce que la sienne donc il la volé

**Comment by LeoBdt** [comment]
nul nul nul

**Comment by LeoBdt** [comment]
oops lol

**Comment by Palente** [comment]
Mais je suis absolument pas ton pote pourquoi tu me mentionnes?

**Comment by LeoBdt** [comment]
@Palente Je te mentionnes si je veux tu t'ai pris pour une star ? je t'ai remit à ta place et tu n'as pas supporté ? aller, dégage

**Comment by Palente** [comment]
Ptdrr, mais retourne fork des plugins au lieu de venir me mentionner

**Comment by LeoBdt** [comment]
T'as aucune répartie le seul truc que j'ai fork c'était pour une traduction, t'es éclaté comme mec

**Comment by Virvolta** [comment]
Ne pas parlé alors que l'issue est fermé merci

**Comment by LeoBdt** [comment]
ok chef

**Comment by Palente** [comment]
Arrete de vouloir faire le mec c'est toi qui est venu me casser les couilles j'en ai rien à faire des randoms comme toi je suis juste venu repondre en disant que c'était virvolta l'auteur mais tu veux faire le mec part de mes mentions

**Comment by LeoBdt** [comment]
écoute, j'ai juste émis un doute sur la provenance du plugin et toi tu pète les couilles, j'ai arrêté de te mention mais tu reste bloqué là dessus. tu es autant random que moi maintenant va bien niquer ta mère et pas la peine de répondre.

**Comment by Hirss** [comment]
bon par contre faite pas les cancers ici si vous voulez vous embrouiller, partez sur discord.

**Comment by Palente** [comment]
On se reverras bientot 😃 on verra qui sera le random
